mod add_plugin;
mod alias;
mod bin;
mod clean;
mod completions;
mod install;
mod install_all;
mod install_global;
mod list;
mod list_global;
mod list_remote;
mod migrate;
mod outdated;
mod pin;
mod plugins;
mod remove_plugin;
mod run;
mod setup;
mod tools;
mod unalias;
mod uninstall;
mod uninstall_global;
mod upgrade;

pub use add_plugin::*;
pub use alias::*;
pub use bin::*;
pub use clean::*;
pub use completions::*;
pub use install::*;
pub use install_all::*;
pub use install_global::*;
pub use list::*;
pub use list_global::*;
pub use list_remote::*;
pub use migrate::*;
pub use outdated::*;
pub use pin::*;
pub use plugins::*;
pub use remove_plugin::*;
pub use run::*;
pub use setup::*;
pub use tools::*;
pub use unalias::*;
pub use uninstall::*;
pub use uninstall_global::*;
pub use upgrade::*;
