name: Bug report
description: File a bug report!
labels: [bug]
assignees: [milesj]
body:
  - type: markdown
    attributes:
      value: |
        If you're reporting an issue for a specific language/tool and not for proto itself, please report the issue on their official repository.
        - [Bun](https://github.com/moonrepo/bun-plugin)
        - [Deno](https://github.com/moonrepo/deno-plugin)
        - [Go](https://github.com/moonrepo/go-plugin)
        - [Node](https://github.com/moonrepo/node-plugin)
        - [Python](https://github.com/moonrepo/python-plugin)
        - [Rust](https://github.com/moonrepo/rust-plugin)
        - [Schema](https://github.com/moonrepo/schema-plugin)
  - type: input
    attributes:
      label: What version?
      description: What version of `proto` are you using?
      placeholder: "0.14.0"
  - type: input
    attributes:
      label: Which command?
      description: Which `proto` command are you reporting the issue for?
      placeholder: proto install
  - type: textarea
    attributes:
      label: What happened?
      description: Please describe the issue you're having and what you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any logs?
      description: If applicable, paste the `--log trace` (or `PROTO_LOG=trace`) output.
  - type: dropdown
    attributes:
      label: Operating system?
      options:
        - Linux
        - MacOS
        - Windows
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Architecture?
      options:
        - x64
        - Arm64
        - Other
    validations:
      required: true
