name: Build binary
description: ""

runs:
  using: composite
  steps:
    - uses: moonrepo/setup-rust@v1
      with:
        cache: true

    - id: download
      uses: actions/download-artifact@v8
      continue-on-error: true
      with:
        name: proto-bins

    - id: build
      run: cargo build --release --bin proto --bin proto-shim
      shell: bash

    - id: upload
      uses: actions/upload-artifact@v7
      with:
        name: proto-bins
        path: |
          target/release/proto
          target/release/proto.exe
          target/release/proto-shim
          target/release/proto-shim.exe
        if-no-files-found: error
