name: E2E

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  e2e:
    name: E2E
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: jlumbroso/free-disk-space@main
        if: ${{ runner.os == 'Linux' }}
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-wasi
          cache: false
          targets: wasm32-wasip1
      - run: cargo build --release --bin proto --bin proto-shim
      - run: cargo build --workspace --target wasm32-wasip1 --release
        working-directory: plugins
      - name: Run E2E
        shell: bash
        run: ./e2e/run.sh
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs-${{ matrix.os }}
          path: e2e/.logs/
